---
usb_modem_device: ttyACM0

# To create: `openssl passwd -6` or `mkpasswd -m sha-512`
dial_user_password: "$6$/.Cbh82jYrdZ/Jgx$AfCLEVtie1SZJzkRbe0PHpNDvCjNP8cw7GcFpWkJc33gCdhZNV4wuDRO5r.0BWTWTFRLM6NbbROxuLPR.M0m20"
